var tagJson = {
    General_CD_Lat: "General_CD_Lat",
    General_Tide: "General_Tide",
    Motion_Roll_Value:"Motion_Roll_Value",
    Motion_Roll_Average: "Motion_Roll_Average",
    Motion_Roll_Maximun: "Motion_Roll_Maximun",
    Motion_Roll_Minimum: "Motion_Roll_Minimum",
    Motion_Roll_Period: "Motion_Roll_Period",
    Motion_Surge_Maximum: "Motion_Surge_Maximum",
    Motion_Surge_Minimum: "Motion_Surge_Minimum",
    Motion_Surge_Average: "Motion_Surge_Average",
    Motion_Surge_Period: "Motion_Surge_Period",
    Motion_Surge_Value:"Motion_Surge_Value",
    Motion_Pitch_Value: "Motion_Pitch_Value",
    Motion_Pitch_Average: "Motion_Pitch_Average",
    Motion_Pitch_Period: "Motion_Pitch_Period",
    Motion_Pitch_Maximum: "Motion_Pitch_Maximum",
    Motion_Pitch_Minimum: "Motion_Pitch_Minimum",
    Motion_Sway_Average: "Motion_Sway_Average",
    Motion_Sway_Maximum: "Motion_Sway_Maximum",
    Motion_Sway_Value:"Motion_Sway_Value",
    Sea_State_Sway_Minimum: "Sea_State_Sway_Minimum",
    Sea_State_Sway_Period: "Sea_State_Sway_Period",
    Sea_State_Wave_Value: "Sea_State_Wave_Value",
    Motion_Yaw_Average: "Motion_Yaw_Average",
    Motion_Yaw_Maximum: "Motion_Yaw_Maximum",
    Motion_Yaw_Minimum: "Motion_Yaw_Minimum",
    Motion_Yaw_Period: "Motion_Yaw_Period",
    Motion_Yaw_Value: "Motion_Yaw_Value",
    Motion_Heave_Average: "Motion_Heave_Average",
    Motion_Heave_Minimum: "Motion_Heave_Minimum",
    Motion_Heave_Period: "Motion_Heave_Period",
    Motion_Heave_Value :"Motion_Heave_Value",
    Sea_State_Significant_Wave_Height: "Sea_State_Significant_Wave_Height",
    Curves_Wave_Period: "Curves_Wave_Period",
    Curves_Maximum_Wave_Height: "Curves_Maximum_Wave_Height",
    General_Water_Depth: "General_Water_Depth",
    General_Vessel_Depth: "General_Vessel_Depth",
    On_Off_Screen_Touchdown_Curve_X_min: "On_Off_Screen_Touchdown_Curve_X_min",
    On_Off_Screen_Touchdown_Curve_X_max:"On_Off_Screen_Touchdown_Curve_X_max",
    On_Off_Screen_Touchdown_Curve_Y_min:"On_Off_Screen_Touchdown_Curve_Y_min",
    On_Off_Screen_Touchdown_Curve_Y_max:"On_Off_Screen_Touchdown_Curve_Y_max",
    Curves_Touchdown_Bubble_X_Value:"Curves_Touchdown_Bubble_X_Value",
    Curves_Touchdown_Bubble_Y_Value:"Curves_Touchdown_Bubble_Y_Value",
    Curves_Sea_State_Bubble_X_Value:"Curves_Sea_State_Bubble_X_Value",
    Curves_Sea_State_Bubble_Y_Value:"Curves_Sea_State_Bubble_Y_Value",
    Sea_State_Period_1:"Sea_State_Period_1",
    Sea_State_Period_2:"Sea_State_Period_2",
    Sea_State_Period_3:"Sea_State_Period_3",
    Sea_State_Period_4:"Sea_State_Period_4",
    Sea_State_Period_5:"Sea_State_Period_5",
    Sea_State_Period_6:"Sea_State_Period_6",
    Sea_State_Period_7:"Sea_State_Period_7",
    Sea_State_Period_8:"Sea_State_Period_8",
    Sea_State_Period_9:"Sea_State_Period_9",
    Sea_State_Period_10:"Sea_State_Period_10",
    Sea_State_Period_11:"Sea_State_Period_11",
    Sea_State_Period_12:"Sea_State_Period_12",
    Sea_State_Period_13:"Sea_State_Period_13",
    Sea_State_Period_14:"Sea_State_Period_14",
    Sea_State_Period_15:"Sea_State_Period_15",
    Sea_State_Period_16:"Sea_State_Period_16",
    Sea_State_Period_17:"Sea_State_Period_17",
    Sea_State_Period_18:"Sea_State_Period_18",
    Sea_State_Period_19:"Sea_State_Period_19",
    Sea_State_Period_20:"Sea_State_Period_20",
    Sea_State_Period_1:"Sea_State_Warning_1",
    Sea_State_Period_2:"Sea_State_Warning_2",
    Sea_State_Period_3:"Sea_State_Warning_3",
    Sea_State_Period_4:"Sea_State_Warning_4",
    Sea_State_Period_5:"Sea_State_Warning_5",
    Sea_State_Period_6:"Sea_State_Warning_6",
    Sea_State_Period_7:"Sea_State_Warning_7",
    Sea_State_Period_8:"Sea_State_Warning_8",
    Sea_State_Period_9:"Sea_State_Warning_9",
    Sea_State_Period_10:"Sea_State_Warning_10",
    Sea_State_Period_11:"Sea_State_Warning_11",
    Sea_State_Period_12:"Sea_State_Warning_12",
    Sea_State_Period_13:"Sea_State_Warning_13",
    Sea_State_Period_14:"Sea_State_Warning_14",
    Sea_State_Period_15:"Sea_State_Warning_15",
    Sea_State_Period_16:"Sea_State_Warning_16",
    Sea_State_Period_17:"Sea_State_Warning_17",
    Sea_State_Period_18:"Sea_State_Warning_18",
    Sea_State_Period_19:"Sea_State_Warning_19",
    Sea_State_Period_20:"Sea_State_Warning_20",
    Touch_Down_Period_1:"Touch_Down_Period_1",
    Touch_Down_Period_2:"Touch_Down_Period_2",
    Touch_Down_Period_3:"Touch_Down_Period_3",
    Touch_Down_Period_4:"Touch_Down_Period_4",
    Touch_Down_Period_5:"Touch_Down_Period_5",
    Touch_Down_Period_6:"Touch_Down_Period_6",
    Touch_Down_Period_7:"Touch_Down_Period_7",
    Touch_Down_Period_8:"Touch_Down_Period_8",
    Touch_Down_Period_9:"Touch_Down_Period_9",
    Touch_Down_Period_10:"Touch_Down_Period_10",
    Touch_Down_Period_11:"Touch_Down_Period_11",
    Touch_Down_Period_12:"Touch_Down_Period_12",
    Touch_Down_Period_13:"Touch_Down_Period_13",
    Touch_Down_Period_14:"Touch_Down_Period_14",
    Touch_Down_Period_15:"Touch_Down_Period_15",
    Touch_Down_Period_16:"Touch_Down_Period_16",
    Touch_Down_Period_17:"Touch_Down_Period_17",
    Touch_Down_Period_18:"Touch_Down_Period_18",
    Touch_Down_Period_19:"Touch_Down_Period_19",
    Touch_Down_Period_20:"Touch_Down_Period_20",
    Touch_Down_Danger_1:"Touch_Down_Danger_1",
    Touch_Down_Danger_2:"Touch_Down_Danger_2",
    Touch_Down_Danger_3:"Touch_Down_Danger_3",
    Touch_Down_Danger_4:"Touch_Down_Danger_4",
    Touch_Down_Danger_5:"Touch_Down_Danger_5",
    Touch_Down_Danger_6:"Touch_Down_Danger_6",
    Touch_Down_Danger_7:"Touch_Down_Danger_7",
    Touch_Down_Danger_8:"Touch_Down_Danger_8",
    Touch_Down_Danger_9:"Touch_Down_Danger_9",
    Touch_Down_Danger_10:"Touch_Down_Danger_10",
    Touch_Down_Danger_11:"Touch_Down_Danger_11",
    Touch_Down_Danger_12:"Touch_Down_Danger_12",
    Touch_Down_Danger_13:"Touch_Down_Danger_13",
    Touch_Down_Danger_14:"Touch_Down_Danger_14",
    Touch_Down_Danger_15:"Touch_Down_Danger_15",
    Touch_Down_Danger_16:"Touch_Down_Danger_16",
    Touch_Down_Danger_17:"Touch_Down_Danger_17",
    Touch_Down_Danger_18:"Touch_Down_Danger_18",
    Touch_Down_Danger_19:"Touch_Down_Danger_19",
    Touch_Down_Danger_20:"Touch_Down_Danger_20"
}
export default tagJson;